### ISSUE TITLE
Type rue non retourné si paramètre en entrée uppercase

### ISSUE THREAD

**Issue by alannagenin** [MaximeChallon/AdresseParser#5]
Bonjour, 

Tout d'abord merci pour le package, il m'est très utile ! 😄 

J'ai remarqué que si l'on passait en paramètre une adresse en majuscules alors le type de rue n'est pas retourné. Voici l'exemple que j'ai expérimenté.

```python
adresse_longue = (adresse.lower() + " " + codePostal + " " + ville.lower())
print(adresse_longue)
adr_parser = AdresseParser()
result = adr_parser.parse(adresse_longue)
print(result)
```
donnera

```
1 place georges agniel 01140 saint didier sur chalaronne
{'numero': '1', 'rue': {'type': 'PLACE', 'nom': 'GEORGES AGNIEL'}, 'code_postal': '01140', 'ville': {'arrondissement': 0, 'nom': 'SAINT DIDIER SUR CHALARONNE'}, 'departement': {'numero': '01', 'nom': 'Ain'}, 'region': 'Auvergne-Rhône-Alpes', 'pays': 'France'}
```

alors que
```python
adresse_longue = (adresse.upper() + " " + codePostal + " " + ville.upper())
print(adresse_longue)
adr_parser = AdresseParser()
result = adr_parser.parse(adresse_longue)
print(result)
```
donnera

```
1 PLACE GEORGES AGNIEL 01140 SAINT DIDIER SUR CHALARONNE
{'numero': '1', 'rue': {'type': '', 'nom': 'GEORGES AGNIEL'}, 'code_postal': '01140', 'ville': {'arrondissement': 0, 'nom': 'SAINT DIDIER SUR CHALARONNE'}, 'departement': {'numero': '01', 'nom': 'Ain'}, 'region': 'Auvergne-Rhône-Alpes', 'pays': 'France'}
```

Alanna

**Comment by MaximeChallon** [comment]
Bonjour, merci pour cette issue. Le code est modifié, et le test sur l'adresse 1 PLACE GEORGES AGNIEL 01140 SAINT DIDIER SUR CHALARONNE est passé.
Au plaisir pour de nouveau ajouts :)

**Comment by alannagenin** [comment]
Merci beaucoup ! 😄 

Il ne faut pas me dire ça, j'ai plusieurs idées d'ajouts en tête ! 🤭 
- [ ] ajouter d'autres types de rue : allée, chemin, route, GR (grande rue), cité, résidence, hameau, lieu-dit, traverse, promenade, rond-point, passage, etc.
- [ ] gérer les adresses avec des indices (1A, 1B, 1C, 1D, ... ou 1 bis, 1 ter, 1 quater, ...)

**Comment by MaximeChallon** [comment]
Voir #6 et #7 ;)
