### ISSUE TITLE
Ajout CEDEX

### ISSUE THREAD

**Issue by alannagenin** [MaximeChallon/AdresseParser#8]
Bonjour,

C'est de nouveau moi ! 🙃 

Pensez-vous qu'il est possible d'ajouter les [CEDEX](https://github.com/MaximeChallon/AdresseParser/files/9220216/liste-des-cedex.csv) ? Le lien est un renvoi vers la liste des CEDEX avec leur code postal, libellé et code INSEE.

Merci par avance ! 😃

**Comment by MaximeChallon** [comment]
C'est fait :)

**Comment by alannagenin** [comment]
Super, merci ! :)

**Comment by alannagenin** [comment]
Super, merci ! 😄 

En l'utilisant ce matin j'ai eu ce message d'erreur :

```python
FileNotFoundError: [Errno 2] No such file or directory: 'AdresseParser/data/liste-des-cedex.csv'
```

En inspectant le code source sur [PyPI](https://pypi.org/project/AdresseParser/#files), il n'y a, en effet, pas de dossier `data` dans cette version.

**Comment by MaximeChallon** [comment]
Arf, je regarde ce soir, il a du être exclu lors du packaging 😔 Je l'avais pourtant testé !

**Comment by MaximeChallon** [comment]
`pip3 install AdresseParser==1.0.9` devrait résoudre le problème
Après téléchargement, j'obtiens:
```
>>> from AdresseParser import AdresseParser
>>> adr_parser = AdresseParser()
>>> print(adr_parser.parse("88 rue de rivoli 75040 paris cedex01"))
{'numero': '88', 'indice': None, 'rue': {'type': 'RUE', 'nom': 'RIVOLI'}, 'code_postal': '75040', 'ville': {'arrondissement': 0, 'nom': 'PARIS'}, 'cedex': [{'libelle': 'PARIS CEDEX 01', 'code_insee': '75101'}, {'libelle': 'PARIS CEDEX 01', 'code_insee': '75114'}], 'departement': {'numero': 75, 'nom': 'Paris'}, 'region': 'Île-de-France', 'pays': 'France'}
```

**Comment by aldevgen** [comment]
Cela fonctionne bien cette fois, merci !
